name: docker-build

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          outputs: type=docker,dest=/tmp/output.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/output.tar
  
  push-docker-hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Load Docker image
        run: docker load -i docker-image

      - name: Retrieve version
        id: retrieve_version
        run: echo "VERSION=${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_ENV

      - name: Tag Docker image
        run: |
          IMAGE_ID=$(docker images -q --filter "dangling=true")
          docker tag $IMAGE_ID ${{ vars.DOCKERHUB_USERNAME }}/my-image:${{ env.VERSION }}
          docker tag $IMAGE_ID ${{ vars.DOCKERHUB_USERNAME }}/my-image:latest

      - name: Push Docker image
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/my-image:${{ env.VERSION }}
          docker push ${{ vars.DOCKERHUB_USERNAME }}/my-image:latest